apiVersion: v1
kind: Service
metadata:
  labels:
    app: quarkus-getting-started
  name: quarkus-getting-started
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: quarkus-getting-started
  sessionAffinity: None
  type: ClusterIP
