apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-app-argo
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: all-openshift-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: 'nginx-app-argo-{{name}}'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/giannisalinetti/rhacm-argocd-integration.git
        targetRevision: main
        path: apps-resources/nginx-app-kustomize/overlays/prod
      destination:
        server: '{{server}}'
        namespace: nginx-app-argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
            - PruneLast=true
            - CreateNamespace=true
